# Generated by Django 4.1.7 on 2023-04-20 10:37

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_files_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='pdf',
            field=models.FileField(upload_to=files.models.generate_filename),
        ),
    ]
