# Generated by Django 4.1.7 on 2023-04-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_difficulty_alter_tasks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='tasks',
            name='max_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
