# Generated by Django 4.1.7 on 2023-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_submissions_studenttaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='teacherstatus',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
